name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ lcov libncurses5-dev
        sudo apt-get install -y g++=4:5.3.1-1ubuntu1
        sudo apt-get install -y lcov=1.12-2
        sudo apt-get install -y cmake=3.5.1-1ubuntu3
        sudo apt-get install -y git=1:2.7.4-0ubuntu1.6
        sudo apt-get install -y libpthread-stubs0-dev=0.3-4

    - name: Build project
      run: |
        cd build
        cmake ..
        make -j8
        

