name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ lcov libncurses5-dev
        sudo apt-get install -y g++
        sudo apt-get install -y lcov
        sudo apt-get install -y cmake
        sudo apt-get install -y git
        sudo apt-get install -y libpthread-stubs0-dev

    - name: Build project
      run: |
        cd build
        cmake ..
        make -j8

    - name: Run tests
      run: |
        cd build
        ./bin/calculator_tests

    - name: Run Coverage
      run: |
        cd build
        cd CMakeFiles/calculator_tests.dir/
        ls -l
        lcov --ignore-errors mismatch -d . -c -o coverage.info
        lcov -r coverage.info */build/* */tests/* */c++/* -o coverageFiltered.info
        lcov --list coverageFiltered.info
      
        

